# Use an official Nginx image
FROM nginx:latest

# Remove the default Nginx configuration
RUN rm -v /etc/nginx/nginx.conf

# Copy your custom Nginx configuration
COPY nginx.conf /etc/nginx/

# Copy the built Vue.js application to the Nginx document root
COPY dist/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
